h_leagues/urls.py
from django.urls import path

from . import views

app_name = 'leagues'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:liga>/', views.league, name='liga'),
    path('<str:liga>/standings', views.standings, name='standings'),
    path('<str:liga>/postseason', views.playoffs, name='postseason'),
    path('<str:liga>/schedule', views.schedule, name='schedule'),
    path('<int:match_id>/simulation', views.simulation, name='simulation')
]

hockey/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('h_leagues.urls'))
]

h_leagues/models.py
from django.db import models
import numpy as np

'''
You can change the leagues names here
'''
LEAGUES = (
    ('OHL', 'Ontario Hockey League'),
    ('QMJHL', 'Quebec Major Junior Hockey League'),
    ('WHL', 'Western Hockey League'),
    ('MMC', 'Memorial Cup')
)

PO_MARKS = (
    (1, 'w - '), # Clinched WildCard Spot
    (2, 'x - '), # Clinched Playoff Spot
    (3, 'y - '), # Division Champion
    (4, 'z - '), # Conference Champion
    (0, '')
)

RESULTADOS = (
    ('', ''),
    ('f', 'FINAL'),
    ('ot', 'FINAL-OT'),
    ('so', 'FINAL-SO'),
)

class League(models.Model): #1
    name= models.CharField(max_length=5, primary_key=True,choices=LEAGUES)
    n_games = models.IntegerField(default=1)
    weeks = models.IntegerField(default=1)
    color = models.CharField(max_length=10, default='')
    bg_color = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.name.upper()

    def get_team(self):
        resp = []
        resp1 = []
        [resp1.append(conf.get_team()) for conf in self.conference_set.all()]
        for line in resp1:
            [resp.append(t) for t in line]
        return resp

    def regular_season(self, season):
        for t in self.get_team():
            rand_off = int(np.random.normal(500, 100))
            rand_def = int(np.random.normal(500, 100))
            RS_clubs(
                t_abr=t, s_year=season, l_name=self,
                off_power=rand_off, def_power=rand_def).save()

    def completeness(self):
        total = self.match_set.count()
        played = total - self.match_set.filter(result='')
        # comp = "%5.2f" % played/total
        return "%d/%d matches (%5.2f %)" % (played, total, (played/total))

class Season(models.Model): #2
    start = models.IntegerField()
    final = models.IntegerField(primary_key=True)
    is_over = models.BooleanField(default=False)

    def __str__(self):
        return "(%d - %d)" % (self.start, self.final)

class Conference(models.Model): #3
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    region = models.CharField(max_length=30)
    wild_card = models.IntegerField(default=0)
    class Meta:
        unique_together = (('league', 'region'))

    def __str__(self):
        return "%s %s Conference" % (self.league, self.region)

    def get_team(self):
        resp = []
        resp1 = []
        [resp1.append(div.get_teams()) for div in self.division_set.all()]
        for line in resp1:
            [resp.append(t) for t in line]
        return resp

    def conf_standings(self):
        tops = []
        wild_c = []
        std = []
        for division in self.division_set.all():
            div = division.div_standings()
            for k in range(division.tops):
                tops.append(div[k])
            for i in range(division.tops,len(div)):
                wild_c.append(div[i])
        tops.sort()
        wild_c.sort()
        [std.append(i) for i in tops]
        [std.append(k) for k in wild_c]
        return  std

class Division(models.Model): #4
    conf = models.ForeignKey(Conference, on_delete=models.CASCADE)
    region = models.CharField(max_length=30)
    tops = models.IntegerField(default=1)
    class Meta:
        unique_together = (('conf', 'region'))

    def __str__(self):
        return "%s %s Division" % (self.conf.league, self.region)

    def get_teams(self):
        resp = []
        [resp.append(t) for t in self.team_set.all()]
        return resp

    def sorted(self):
        vec = []
        [vec.append(rs.rs_clubs_set.last()) for rs in self.get_teams()]
        vec.sort()
        rank = 1
        for rs_clubs in vec:
            rs_clubs.div_placement = rank
            rank += 1
            rs_clubs.save()
        return vec

    def div_standings(self):
        vec = []
        [vec.append(team) for team in self.get_teams()]
        vec.sort()
        return vec

class Team(models.Model): #5
    city = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    abr = models.CharField(max_length=5, primary_key=True)
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    bg_color = models.CharField(max_length=10, default='')
    l_championship = models.IntegerField(default=0)
    mmc_championship = models.IntegerField(default=0)

    def __str__(self):
        return "%s %s" % (self.city, self.name)

    def __lt__(self, other):
        this = self.rs_clubs_set.last()
        that =  other.rs_clubs_set.last()
        return this.div_placement < that.div_placement

class RS_clubs(models.Model): #6
    t_abr = models.ForeignKey(Team, on_delete=models.CASCADE)
    s_year = models.ForeignKey(Season, on_delete=models.CASCADE)
    l_name = models.ForeignKey(League, on_delete=models.CASCADE)
    seed = models.IntegerField(default=1)
    po_marks = models.IntegerField(default=0, choices=PO_MARKS)
    pts = models.IntegerField(default=0)
    wins = models.IntegerField(default=0)
    loss = models.IntegerField(default=0)
    otl = models.IntegerField(default=0)
    sol = models.IntegerField(default=0)
    gf = models.IntegerField(default=0)
    ga = models.IntegerField(default=0)
    diff = models.IntegerField(default=0)
    last5 = models.CharField(default=' - - - - ', max_length= 15)
    streak = models.CharField(max_length=3, default='W 0')
    div_placement = models.IntegerField(default=1)
    games = models.ManyToManyField("self", through='Match', through_fields=('home', 'away'))
    off_power = models.IntegerField(default=500)
    momentum = models.IntegerField(default=500)
    def_power = models.IntegerField(default=500)
    class Meta:
        unique_together=(('t_abr', 's_year'), )

    # this class and subsequent methods can be changed according to the sport to be simulated

    def __lt__(self, other):
        if self.pts != other.pts:
            return self.pts > other.pts
        elif self.diff != other.diff:
            return self.diff > other.diff
        elif self.gf != other.gf:
            return self.gf > other.gf
        elif self.t_abr.city != other.t_abr.city:
            return  self.t_abr.city < other.t_abr.city

    def __str__(self):
        return "%s %s" % (self.t_abr, self.s_year)

    def seq(self, result):
        r = (self.streak).split(" ")
        if result == r[0]:
            s = int(r[1]) + 1
            self.streak = "%s %d" % (r[0], s)
            self.save()
        else:
            self.streak = "%s 1" % result
            self.save()

    def games(self):
        return self.wins + self.loss + self.otl + self.sol

    def pct(self):
        jogos = self.games()
        if jogos == 0:
            return '0.000'
        else:
            return '%05.3f' % (self.pts/(jogos*2))

    def campaign(self):
        return "%s - %s - %s - %s" % (self.wins, self.loss, self.otl, self.sol)

    def l5(self, result):
        vec = [result] + self.last5.split('-')[:4]
        self.last5 = '%s - %s - %s - %s - %s' % (vec[0], vec[1], vec[2], vec[3], vec[4])
        self.save()


class PostSeason(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    wins = models.IntegerField(default=0)
    loss = models.IntegerField(default=0)
    end_point = models.CharField(default='', max_length=20)
    participates = models.ManyToManyField('self', through='Series', symmetrical=False)
    class Meta:
        unique_together= (('team', 'season'),)

    def __str__(self):
        return "%s  (%s - %s)" % (self.team, self.wins, self.loss)

class Series(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    phase = models.IntegerField()
    high = models.ForeignKey(PostSeason, on_delete=models.CASCADE, related_name='higher')
    h_wins = models.IntegerField(default=1)
    low = models.ForeignKey(PostSeason, on_delete=models.CASCADE, related_name='lower')
    l_wins = models.IntegerField(default=1)
    conf = models.IntegerField(default=0)
    title = models.CharField(max_length=20, default='')
    class Meta:
        unique_together= (('league', 'season', 'phase', 'high', 'low'),)

    def __str__(self):
        return "#%s%s Rd%d %d" % (self.high,self.low,self.phase,
                self.season.final)

class Match(models.Model):
    away = models.ForeignKey(RS_clubs, on_delete=models.CASCADE, related_name='guest')
    a_score = models.IntegerField(default=0)
    a_rec = models.CharField(max_length=15, default='')
    home = models.ForeignKey(RS_clubs, on_delete=models.CASCADE, related_name='host')
    h_score = models.IntegerField(default=0)
    h_rec = models.CharField(max_length=15, default='')
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    result = models.CharField(max_length=2, choices=RESULTADOS, default='')

    # def __init__(self):

    def __lt__(self, other):
        return self.id > other.id

class PSMatch(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    game = models.IntegerField(default=1)
    h_score = models.IntegerField(default=0)
    a_score = models.IntegerField(default=0)
    result = models.CharField(max_length=15, default='')
    storyline = models.CharField(max_length=40, default='')

class Winners(models.Model):
    champion = models.ForeignKey(Team, on_delete=models.CASCADE)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    div_champ = models.BooleanField(default=False)
    division = models.CharField(max_length=10, default='')
    host = models.CharField(max_length=20, default='')

    def champs(self):
        if self.league.name == 'MMC':
            self.champion.mmc_championship += 1
            if self.champion.save():
                print('OK')
        else:
            self.champion.l_championship += 1
            if self.champion.save():

h_leagues/templates/h_leagues/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Canadien Hockey League -- my django APP</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="base.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<nav>
    <div class="nav-wrapper">
        <a href="{% url 'leagues:index' %}" class="brand-logo center"
           style="font-weight: bolder; font-family: 'Lobster Two'; font-size: 45px"> Canadien Hockey League </a>
    </div>
</nav>

<div class="row" style="padding-top: 1em">
    <div class="col l3">
        <!-- Painel -->
        {% if ll %}
            {% for league in ll %}
              <ul class="collection with-header" style="font-weight: bolder">
                <li class="collection-header {{ league.bg_color }}-text {{ league.color }}">
                    <h5>{{ league.get_name_display }}</h5></li>
                <li class="collection-item {{ league.color }}-text {{ league.bg_color }} lighten-2">
                    <div>Standings <a href="{% url 'leagues:standings' league.name %}" class="secondary-content"><i class="material-icons {{ league.color }}-text">send</i></a></div></li>
                <li class="collection-item {{ league.color }}-text {{ league.bg_color }} lighten-2">
                    <div>Schedule<a href="{% url 'leagues:schedule' league.name %}" class="secondary-content"><i class="material-icons {{ league.color }}-text">send</i></a></div></li>
                <li class="collection-item {{ league.color }}-text {{ league.bg_color }} lighten-2">
                    <div>Playoffs<a href="{% url 'leagues:postseason' league.name %}" class="secondary-content"><i class="material-icons {{ league.color }}-text">send</i></a></div></li>
                <li class="collection-item {{ league.color }}-text {{ league.bg_color }} lighten-2">
                    <div>Past Winners<a href="{% url 'leagues:liga' league.name %}" class="secondary-content"><i class="material-icons {{ league.color }}-text">send</i></a></div></li>
              </ul>
            {% endfor %}
                    
        {% endif %}

        {% block chips %}

        {% endblock %}
    </div>

    <div class="col l9">
        {% if l %}
              <nav style="font-weight: bolder"
                   class="{{ l.color }} {{ l.bg_color }}-text">
                <div class="nav-wrapper">
                  <a href="#" class="brand-logo right" style="font-size: 32px"> {{ l.get_name_display }} </a>
                  <ul id="nav-mobile" class="left hide-on-med-and-down">
                      <li><a href="{% url 'leagues:standings' l.name %}">Standings</a></li>
                      <li><a href="">Matches </a></li>
                      <li><a href="">Playoffs</a></li>
                      {% if winner %}
                          <li> C: {{ winner.first.champion }} </li>
                      {% endif %}
                  </ul>
                </div>
              </nav>
        {% endif %}


        {% block mainblock %}
        
        {% endblock %}
    </div>
</div>

</body>
</html>

h_leagues/templates/h_leagues/index.html
{% extends 'h_leagues/base.html' %}

{% block mainblock %}

    <h2> Season {{ past }} </h2> <hr>

    <ul>
        <li> President Cup (QMJHL):
            <span style="font-weight: bolder"> {{ qhl.champion }} </span> </li>
        <li> J. Ross Robertson Throphy (OHL):
            <span style="font-weight: bolder"> {{ ohl.champion }} </span> </li>
        <li> Ed Chynoweth Cup (WHL):
            <span style="font-weight: bolder"> {{ whl.champion }} </span> </li>
        <li> Memorial Cup:
            <span style="font-weight: bolder"> {{ mmc.champion }} </span> </li>
    </ul>

{#    <div class="row">#}
{#        <div class="col l4 card z-depth-2">#}
{#            <h4 class="header"> QMJHL </h4>#}
{#            {% for q in qmjhl %}#}
{#                <p> {{ q.away }} @ {{ q.home }} <button class="btn waves-effect waves-light">Play#}
{#                    <i class="material-icons">play_circle_filled</i></button> </p> <hr>#}
{#            {% endfor %}#}
{#        </div>#}
{#        <div class="col l4 card z-depth-2">#}
{#            <h4 class="header"> OHL </h4>#}
{#            {% for o in ohl %}#}
{#                <p> {{ o.away }} @ {{ o.home }} <button class="btn waves-effect waves-light">Play#}
{#                    <i class="material-icons">play_circle_filled</i></button> </p> <hr>#}
{#            {% endfor %}#}
{#        </div>#}
{#        <div class="col l4 card z-depth-2">#}
{#            <h4 class="header"> WHL </h4>#}
{#            {% for w in whl %}#}
{#                <p> {{ w.away }} @ {{ w.home }} <button class="btn waves-effect waves-light">Play#}
{#                    <i class="material-icons">play_circle_filled</i></button> </p> <hr>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}
{##}
{#<table class="striped z-depth-4">#}
{#            <thead>#}
{#                <tr>#}
{#                    <th> # </th>#}
{#                    <th> CHL Top 15 </th>#}
{#                    <th> Pts </th>#}
{#                    <th> G </th>#}
{#                    <th> W </th>#}
{#                    <th> L </th>#}
{#                    <th> OTL </th>#}
{#                    <th> SOL </th>#}
{#                    <th> GF </th>#}
{#                    <th> GA </th>#}
{#                    <th> DIFF </th>#}
{#                    <th> PCT </th>#}
{#                    <th> Streak </th>#}
{#                </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#            {% for qw in teams %}#}
{#                <tr>#}
{#                    <th> {{ forloop.counter }} </th>#}
{#                    {% if qw.league == 'OHL' %}#}
{#                        <th> {{ qw.city }} {{ qw.name }}#}
{#                            <span class="badge blue lighten-5 blue-text" style="font-size: x-small">#}
{#                                {{ qw.league.upper }} </span> </th>#}
{#                    {% elif qw.league == 'WHL' %}#}
{#                        <th> {{ qw.city }} {{ qw.name }}#}
{#                            <span class="badge red lighten-5 red-text" style="font-size: x-small">#}
{#                                {{ qw.league.upper }} </span> </th>#}
{#                    {% else %}#}
{#                        <th> {{ qw.city }} {{ qw.name }}#}
{#                            <span class="badge gray lighten-2" style="font-size: x-small">#}
{#                                {{ qw.league.upper }} </span> </th>#}
{#                    {% endif %}#}
{#                    <th> {{ qw.pts }} </th>#}
{#                    <th> {{ qw.games }}</th>#}
{#                    <th> {{ qw.wins }}</th>#}
{#                    <th> {{ qw.loss }}</th>#}
{#                    <th> {{ qw.otl }} </th>#}
{#                    <th> {{ qw.sol }}</th>#}
{#                    <th> {{ qw.gf }} </th>#}
{#                    <th> {{ qw.ga }} </th>#}
{#                    <th> {{ qw.diff }} </th>#}
{#                    <th> {{ qw.pct }} </th>#}
{#                    <th> {{ qw.streak }}</th>#}
{#                </tr>#}
{#            {% endfor %}#}
{#            </tbody>#}
{#        </table>#}

    <table class="highlight z-depth-3">
        <thead>
            <tr>
                <th> Hall of Honor </th>
                <th> Memorial Cup Titles </th>
                <th> League Titles </th>
            </tr>
        </thead>
        <tbody>
            {% for team in teams %}
                <tr>
                    <td> {{ team }} </td>
                    <td> {{ team.mmc_championship }} </td>
                    <td> {{ team.l_championship }} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


{% endblock %}

h_leagues/templates/h_leagues/leagues.html
{% extends 'h_leagues/base.html' %}

{% block mainblock %}



{% endblock %}

h_leagues/templates/h_leagues/match.html
{% extends 'h_leagues/base.html' %}

{% block mainblock %}
    <a href="{% url 'leagues:schedule' partida.league %}"> Back to {{ partida.league }} schedule (Temporary View) </a>

    <div class="row">
        <div class="col s6" style="font-size: large;font-weight: bolder">
            {{ fora }}
        </div>
        <div class="col s6" style="font-size: large;font-weight: bolder">
            {{ casa }}
        </div>
    </div>
    <div class="row">
        <div class="col s6" style="font-size: 40px;font-weight: bolder;align-content: center"> {{ partida.a_score }}</div>
        <div class="col s6" style="font-size: 40px;font-weight: bolder;align-content: center"> {{ partida.h_score }}</div>
    </div>

    {% if partida.resultado == 'f' %}
        <h2 style="font-weight: bolder"> {{ victory.name }} wins in Regulation </h2>
    {% elif partida.resultado == 'ot' %}
        <h2 style="font-weight: bolder"> {{ victory.name }} wins in OT </h2>
    {% elif partida.resultado == 'so' %}
        <h2 style="font-weight: bolder"> {{ victory.name }} wins in <SO></SO> </h2>
    {% endif %}
{% endblock %}

h_leagues/templates/h_leagues/schedule.html
{% extends 'h_leagues/base.html' %}

{% block chips %}
    {% if msg %}
        <div class="chip" style="font-size: larger; font-weight: bolder"> {{ msg }} </div>
        <div class="chip" style="font-size: larger; font-weight: bolder"> {{ result }} </div>
    {% endif %}
{% endblock %}

{% block mainblock %}
    <div class="row">
        <h3>Schedule</h3> <hr>
        {% for matches in nP %}
            <div class="col s6 m6 l6">
                <ul class="collection with-header"
                    style="font-weight: bolder">
                    <li class="collection-header black white-text"> Match {{ matches.id }}
                    <a href="{% url 'leagues:simulation' matches.id %}" class="secondary-content {{ l.color }}-text"> Play <i class="material-icons">send</i></a></li>
                    <li class="collection-item white-text {{ matches.away.t_abr.bg_color }} darken-4"> {{ matches.away.t_abr }} <span class="secondary-content {{ matches.away.t_abr.bg_color }} darken-4 white-text"> {{ matches.away.campaign }} </span>
                    <li class="collection-item white-text {{ matches.home.t_abr.bg_color }} darken-4"> {{ matches.home.t_abr }} <span class="secondary-content {{ matches.home.t_abr.bg_color }} darken-4 white-text"> {{ matches.home.campaign }}  </span>
                </ul>
            </div>
        {% endfor %}

        <br><br> <h3>Played</h3>
        {% for matches in P %}
            <div class="col s6 m6 l6">
                <ul class="collection with-header"
                    style="font-weight: bolder">
                    <li class="collection-header black white-text"> Match {{ matches.id }}
                    <a href="{% url 'leagues:simulation' matches.id %}" class="secondary-content {{ l.color }}-text"> Play <i class="material-icons">send</i></a></li>
                    <li class="collection-item white-text {{ matches.away.t_abr.bg_color }} darken-4"> {{ matches.away.t_abr }} <span class="secondary-content {{ matches.away.t_abr.bg_color }} darken-4 white-text"> {{ matches.a_score }} </span>
                    <li class="collection-item white-text {{ matches.home.t_abr.bg_color }} darken-4"> {{ matches.home.t_abr }} <span class="secondary-content {{ matches.home.t_abr.bg_color }} darken-4 white-text"> {{ matches.h_score }}  </span>
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}

h_leagues/templates/h_leagues/standings.html
{% extends 'h_leagues/base.html' %}

{% block mainblock %}

      <div class="row">
        <div class="col s12 m9 l10">
            {% for conferencia in l.conference_set.all %}
                <h3 style="border-bottom: 1em solid {{ l.bg_color }}"> {{ conferencia.region }} Conference </h3>
                {% for division in conferencia.division_set.all %}
                    <div id="{{ division.region }}division" class="section scrollspy">
                        <table class="striped z-depth-4">
                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th> {{ division.region }} Division </th>
                                    <th> Pts </th>
                                    <th> G </th>
                                    <th> W </th>
                                    <th> L </th>
                                    <th> OTL </th>
                                    <th> SOL </th>
                                    <th> GF </th>
                                    <th> GA </th>
                                    <th> DIFF </th>
                                    <th> PCT </th>
                                    <th> Streak </th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for qw in division.div_standings %}
                                {% if forloop.counter <= division.tops %}
                                    <tr class="{{ l.color }} {{ l.bg_color }}-text">
                                {% else %}
                                    <tr>
                                {% endif %}
                                    <th> {{ forloop.counter }} </th>
                                    <th> {{ qw.city }} {{ qw.name }} </th>
                                    <th> {{ qw.rs_clubs_set.last.pts }} </th>
                                    <th> {{ qw.rs_clubs_set.last.games }}</th>
                                    <th> {{ qw.rs_clubs_set.last.wins }}</th>
                                    <th> {{ qw.rs_clubs_set.last.loss }}</th>
                                    <th> {{ qw.rs_clubs_set.last.otl }} </th>
                                    <th> {{ qw.rs_clubs_set.last.sol }}</th>
                                    <th> {{ qw.rs_clubs_set.last.gf }} </th>
                                    <th> {{ qw.rs_clubs_set.last.ga }} </th>
                                    <th> {{ qw.rs_clubs_set.last.diff }} </th>
                                    <th> {{ qw.rs_clubs_set.last.pct }} </th>
                                    <th> {{ qw.rs_clubs_set.last.streak }}</th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endfor %}

            {% endfor %}

          <div id="seeds" class="section scrollspy">
            {% for conference in l.conference_set.all %}
                <table class="striped z-depth-4">
                    <thead>
                        <tr>
                            <th> # </th>
                            <th> {{ conference.region }} Conference </th>
                            <th> Pts </th>
                            <th> G </th>
                            <th> W </th>
                            <th> L </th>
                            <th> OTL </th>
                            <th> SOL </th>
                            <th> GF </th>
                            <th> GA </th>
                            <th> DIFF </th>
                            <th> PCT </th>
                            <th> Streak </th>
                        </tr>
                    </thead>
                    <tbody style="font-weight: bold">
                    {% for qw in conference.conf_standings %}
                        {% if forloop.counter <= tops %}
                            <tr class="{{ l.color }} {{ l.bg_color }}-text">
                                <td> {{ forloop.counter }} </td>
                        {% elif forloop.counter > poff %}
                            <tr>
                                <td></td>
                        {% else %}
                            <tr  class="{{ l.bg_color }} {{ l.color }}-text"
                                style="border-bottom: {{ l.bg_color }}">
                                <td> {{ forloop.counter }} </td>
                        {% endif %}
                            <td> {{ qw.city }} {{ qw.name }} </td>
                            <td> {{ qw.rs_clubs_set.last.pts }} </td>
                            <td> {{ qw.rs_clubs_set.last.games }}</td>
                            <td> {{ qw.rs_clubs_set.last.wins }}</td>
                            <td> {{ qw.rs_clubs_set.last.loss }}</td>
                            <td> {{ qw.rs_clubs_set.last.otl }} </td>
                            <td> {{ qw.rs_clubs_set.last.sol }}</td>
                            <td> {{ qw.rs_clubs_set.last.gf }} </td>
                            <td> {{ qw.rs_clubs_set.last.ga }} </td>
                            <td> {{ qw.rs_clubs_set.last.diff }} </td>
                            <td> {{ qw.rs_clubs_set.last.pct }} </td>
                            <td> {{ qw.rs_clubs_set.last.streak }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endfor %}

          </div>
        </div>
        <div class="col hide-on-small-only m3 l2">
          <ul class="section table-of-contents">
            {% for conference in l.conference_set.all %}
                {% for division in conference.division_set.all %}
                    <li><a href="#{{ division.region }}division"> {{ division }} </a></li>
                {% endfor %}

            {% endfor %}

            <li><a href="#seeds">Conference Standings</a></li>
          </ul>
        </div>
      </div>


{% endblock %}